# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Runs tests in AWS DeviceFarm'
  lane :test_in_aws_devicefarm do
    run_started = Time.now.to_i.to_s
    send_message_to_sqs(
      queue_name: 'LearnCloud-Devicefarm-Listener',
      message_body: 'DeviceFarmRunInProcess',
      message_attributes: {
        'RunArn' => {
          string_value: 'arn:aws:devicefarm:us-west-2:125325355814:run:1106f40e-69a9-42b4-858c-40ecbe6d816d/185f6541-13c8-4345-80c6-d41a1b4ee679',
          data_type: 'String'
        },
        'RunStarted' => {
          string_value: run_started,
          data_type: 'Number'
        }
      }
    )
  end
end
