# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Runs tests in AWS DeviceFarm'
  lane :test_in_aws_devicefarm do
    run_started = Time.now.to_i.to_s

    xcodebuild(
      scheme: 'UITests',
      destination: 'generic/platform=iOS',
      configuration: 'Release',
      derivedDataPath: 'aws-tmp',
      xcargs: 'ENABLE_BITCODE=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build-for-testing'
    )
  end
end
